# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\"\x1e\n\x0eRequestPayload\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fResponsePayload\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\nHelloWorld\x12/\n\x08Greeting\x12\x0f.RequestPayload\x1a\x10.ResponsePayload\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTPAYLOAD']._serialized_start=21
  _globals['_REQUESTPAYLOAD']._serialized_end=51
  _globals['_RESPONSEPAYLOAD']._serialized_start=53
  _globals['_RESPONSEPAYLOAD']._serialized_end=87
  _globals['_HELLOWORLD']._serialized_start=89
  _globals['_HELLOWORLD']._serialized_end=150
# @@protoc_insertion_point(module_scope)
